const GET_ALL_USERS = "GET_ALL_USERS";
const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
const ADD_CATEGORY = "ADD_CATEGORY";
// const DELETE_CATEGORY = "DELETE_CATEGORY"
const ADD_PRODUCT = "ADD_PRODUCT";
const GET_PRODUCT_DATA_TO_UPDATE = "GET_PRODUCT_DATA_TO_UPDATE"
const GET_TODO_DETAIL = "GET_TODO_DETAIL";
const SET_IS_FETCHING = "SET_IS_FETCHING";
const UPDATE_PRODUCT = "UPDATE_PRODUCT";
const DELETE_USER = "DELETE_USER";
const DELETE_CATEGORY = "DELETE_CATEGORY";
const DELETE_PRODUCT = "DELETE_PRODUCT";
const CREATE_TODO = "CREATE_TODO";
const UPDATE_CATEGORY = "UPDATE_CATEGORY";
const GET_CATEGORY_DATA_TO_UPDATE = "GET_CATEGORY_DATA_TO_UPDATE";
const LOGIN = "LOGIN";
export const FETCH_USER = "FETCH_USER";
export const FETCH_LOADING = "FETCH_LOADING";
const LOGIN_LOADING = "LOGIN_LOADING";
const REGISTER = "REGISTER";
const REGISTER_LOADING = "REGISTER_LOADING";
const SET_IS_FETCHING_TODOS = "SET_IS_FETCHING_TODOS";


export {
  SET_IS_FETCHING_TODOS,
  GET_PRODUCT_DATA_TO_UPDATE,
  SET_IS_FETCHING,
  ADD_CATEGORY,
  UPDATE_PRODUCT,
  ADD_PRODUCT,
  DELETE_PRODUCT,
  DELETE_CATEGORY,
  GET_ALL_USERS,
  GET_ALL_CATEGORIES,
  GET_ALL_PRODUCTS,
  GET_TODO_DETAIL,
  DELETE_USER,
  UPDATE_CATEGORY,
  CREATE_TODO,
  GET_CATEGORY_DATA_TO_UPDATE,
  LOGIN,
  LOGIN_LOADING,
  REGISTER,
  REGISTER_LOADING
};