const GET_ALL_USERS = "GET_ALL_USERS";
const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
const GET_TODO_DETAIL = "GET_TODO_DETAIL";
const DELETE_USER = "DELETE_USER";
const CREATE_TODO = "CREATE_TODO";
const UPDATE_TODO = "UPDATE_TODO";
const GET_TODO_DATA_TO_UPDATE = "GET_TODO_DATA_TO_UPDATE";
const LOGIN = "LOGIN";
export const FETCH_USER = "FETCH_USER";
export const FETCH_LOADING = "FETCH_LOADING";
const LOGIN_LOADING = "LOGIN_LOADING";
const REGISTER = "REGISTER";
const REGISTER_LOADING = "REGISTER_LOADING";
const SET_IS_FETCHING_TODOS = "SET_IS_FETCHING_TODOS";


export {
  SET_IS_FETCHING_TODOS,
  GET_ALL_USERS,
  GET_ALL_CATEGORIES,
  GET_TODO_DETAIL,
  DELETE_USER,
  UPDATE_TODO,
  CREATE_TODO,
  GET_TODO_DATA_TO_UPDATE,
  LOGIN,
  LOGIN_LOADING,
  REGISTER,
  REGISTER_LOADING
};